import airportKeywords from './airportKeywords.js';

export default [
  {
    slug: 'airport', title: '机场推荐', eyebrow: 'Service Directory', icon: 'globe',
    description: '从服务入口、线路类型、价格周期和实际场景出发，建立可核验的机场选择清单。',
    intro: '机场推荐不是一次测速后的简单排名。本页先提供已明确标注推广关系的服务入口，再通过主题知识地图连接选择指南、线路说明、客户端教程和故障排查内容。服务价格、套餐、线路与可用性可能变化，访问第三方页面后请再次核验。',
    highlights: ['推广关系清楚标注', '选择维度统一透明', '入口与教程相互连接'],
    entries: [
      { title: '2026 机场推荐与场景榜单', description: '按稳定性、晚高峰、流媒体、AI、游戏和办公需求整理选择逻辑。', url: '/blog/airport-recommendations-2026/' },
      { title: '新手机场选择指南', description: '从协议、线路、倍率、设备数、付款周期到跑路风险逐项判断。', url: '/blog/airport-selection-guide/' },
      { title: '机场价格与套餐', description: '比较月付、季付、年付、流量包、试用和优惠码的真实成本。', url: '/blog/airport-pricing-guide/' },
      { title: '线路与 IP 类型', description: '理解直连、中转、BGP、IPLC、原生 IP 和住宅 IP 的差别。', url: '/blog/airport-line-types/' },
      { title: '地区节点指南', description: '梳理香港、日本、新加坡、美国等节点的距离、线路与适用场景。', url: '/blog/airport-regional-nodes/' },
      { title: '连接故障排查', description: '处理速度慢、延迟高、订阅失败、节点不显示和连接超时。', url: '/blog/airport-troubleshooting/' },
    ],
    keywordGroups: airportKeywords,
    providers: [
      { name: '光年梯', mark: '光', label: '推广链接', description: '查看光年梯的服务页面、当前套餐与注册信息，具体内容以服务方页面为准。', url: 'https://Rumors.gntaff.com/#/?code=Mclks3w5' },
      { name: '云图机场', mark: '云', label: '推广链接', description: '查看云图机场的服务页面、当前套餐与注册信息，具体内容以服务方页面为准。', url: 'https://super.ytjcok.org/#/register?code=COsTypDq' },
      { name: '鲲鹏加速', mark: '鲲', label: '推广链接', description: '查看鲲鹏加速的服务页面、当前套餐与注册信息，具体内容以服务方页面为准。', url: 'https://kunpengjiasu.com/#/register?code=Yd7XpCEQ' },
    ],
    faqs: [
      { question: '推荐入口是否包含推广链接？', answer: '是。标有“推广链接”的按钮可能包含本站推广参数；套餐、价格、退款规则与实际可用性均以服务方页面为准。' },
      { question: '推荐顺序代表绝对排名吗？', answer: '不代表。不同地区、运营商、设备和使用时段会得到不同结果，本站更强调选择维度与核验方法。' },
      { question: '第一次购买应该选择多久？', answer: '优先选择小额月付或明确的试用方案，在自己的常用网络和晚高峰时段完成验证后再决定是否续费。' },
    ],
  },
  {
    slug: 'reviews', title: '机场评测', eyebrow: 'Independent Reviews', icon: 'shield',
    description: '用可复查的条件记录线路、速度、晚高峰表现、客户端体验与服务透明度。',
    intro: '评测栏目将事实资料、实测记录和主观判断分开呈现。阅读任何结论时，都应同时查看测试日期、地区、运营商、设备、客户端版本和测试时段。',
    highlights: ['注明测试环境', '区分事实与体验', '保留更新与修订记录'],
    entries: [
      { title: '标准评测框架', description: '了解本站如何记录测试环境、线路信息、速度、稳定性和结论边界。', url: '/blog/review-framework/' },
      { title: '机场推荐方法', description: '把服务排行拆解为晚高峰、线路、设备、流量和运营信息五个维度。', url: '/blog/airport-recommendations-2026/' },
      { title: '线路质量判断', description: '避免只看线路名称，学会结合入口、中转、落地和路由表现判断。', url: '/blog/airport-line-types/' },
      { title: '倍率与审计规则', description: '检查流量倍率、设备限制、服务条款和日志审计边界。', url: '/blog/airport-multiplier-audit/' },
      { title: '价格价值判断', description: '将有效流量、稳定时段和支持成本纳入价格比较。', url: '/blog/airport-pricing-guide/' },
      { title: '使用场景评测', description: '分别评估流媒体、AI、外贸、直播、办公和学术需求。', url: '/blog/airport-use-cases/' },
    ],
    faqs: [
      { question: '为什么同一机场的评价差异很大？', answer: '用户所在地、运营商、路由、客户端和测试时段不同，同一服务可能出现明显差异，因此评测必须说明环境。' },
      { question: '测速数字越高就越好吗？', answer: '不一定。日常体验还取决于连接成功率、延迟、抖动、丢包和晚高峰持续带宽。' },
      { question: '本站会接受服务方合作吗？', answer: '可以沟通，但合作关系会明确标注，不应改变测试条件、风险提示和结论边界。' },
    ],
  },
  {
    slug: 'guides', title: '客户端教程', eyebrow: 'Step-by-step Guides', icon: 'book',
    description: '覆盖订阅导入、平台配置、客户端选择和常见错误处理，步骤清晰可复查。',
    intro: '教程会先说明系统、版本和前置条件，再给出操作步骤、检查点与失败后的回退方式。涉及第三方软件时，优先建议从官方仓库或可信应用商店获取。',
    highlights: ['先说明系统与版本', '每一步都有检查点', '失败后提供排查顺序'],
    entries: [
      { title: '订阅链接与一键导入', description: '理解订阅地址的作用，并在 Clash、Shadowrocket 等客户端中完成导入。', url: '/blog/airport-subscription-guide/' },
      { title: '协议与客户端区别', description: '区分 SS、SSR、V2Ray、Trojan、订阅格式与客户端软件。', url: '/blog/airport-protocol-client-guide/' },
      { title: 'Windows、Mac 与移动端', description: '按 Windows、macOS、Android 和 iOS 选择合适客户端。', url: '/blog/airport-device-platform-guide/' },
      { title: '连接故障排查', description: '从系统时间、订阅状态、代理模式、DNS 和节点逐层定位问题。', url: '/blog/airport-troubleshooting/' },
      { title: '客户端安装检查清单', description: '下载、安装、导入、连通性测试和更新前备份的标准流程。', url: '/blog/client-checklist/' },
      { title: '新手完整选择路径', description: '把服务选择、客户端配置与首轮测试串成一条完整路径。', url: '/blog/airport-selection-guide/' },
    ],
    faqs: [
      { question: '订阅链接可以直接在浏览器打开吗？', answer: '通常不需要。订阅链接应导入兼容客户端，直接在浏览器打开可能显示编码文本或触发下载。' },
      { question: '为什么导入后没有节点？', answer: '先检查订阅是否过期、客户端是否兼容、系统时间是否准确，再尝试更新订阅或重新添加。' },
      { question: '客户端应该从哪里下载？', answer: '优先使用官方仓库、官方网站或可信应用商店，并核对项目名称、开发者和版本信息。' },
    ],
  },
  {
    slug: 'downloads', title: '客户端下载', eyebrow: 'Client Library', icon: 'download',
    description: '按平台和协议整理客户端下载判断方法、官方来源识别与安装前检查事项。',
    intro: '不同客户端支持的系统、协议和配置格式并不相同。下载前应确认操作系统版本、处理器架构、项目维护状态和订阅兼容性，不从陌生群聊或网盘获取来历不明的安装包。',
    highlights: ['优先官方来源', '核对平台与架构', '安装前保留旧配置'],
    entries: [
      { title: 'Windows 客户端', description: '了解 Clash Verge、Clash Meta、v2rayN 等工具的定位和选择方法。', url: '/blog/airport-device-platform-guide/' },
      { title: 'macOS 客户端', description: '核对 Intel 与 Apple 芯片架构、系统权限和订阅格式。', url: '/blog/airport-device-platform-guide/' },
      { title: 'Android 客户端', description: '比较 v2rayNG、Clash 系客户端和 sing-box 生态的适用范围。', url: '/blog/airport-protocol-client-guide/' },
      { title: 'iOS 客户端', description: '了解 Shadowrocket、Quantumult X、Stash 的获取与导入注意事项。', url: '/blog/airport-device-platform-guide/' },
      { title: '安装前检查清单', description: '检查系统版本、架构、下载来源、权限提示和配置备份。', url: '/blog/client-checklist/' },
      { title: '导入失败处理', description: '处理订阅格式不兼容、更新失败和配置解析错误。', url: '/blog/airport-subscription-guide/' },
    ],
    faqs: [
      { question: '本站是否直接提供安装包？', answer: '本站以下载判断、官方来源识别和配套教程为主；涉及安装包时会优先指向项目官方来源。' },
      { question: '旧版 Clash for Windows 还能继续使用吗？', answer: '应先核对项目维护状态和安全风险。长期使用不再维护的软件会增加兼容性与安全问题。' },
      { question: '更新客户端前要做什么？', answer: '备份订阅地址、规则与自定义配置，记录当前可用版本，确认新版本支持自己的系统和协议。' },
    ],
  },
  {
    slug: 'ai-tools', title: 'AI 工具推荐', eyebrow: 'AI Toolkit', icon: 'bot',
    description: '从写作、搜索、图像、音视频和效率工作流出发，整理 AI 工具选择方法。',
    intro: 'AI 工具会快速调整功能、价格和地区政策。本栏目更关注适用任务、输入输出质量、隐私边界、费用结构与替代方案，不把一次体验写成永久结论。',
    highlights: ['按真实任务分类', '关注隐私与费用', '记录最近核验日期'],
    entries: [
      { title: 'AI 与网络环境', description: '了解地区可用性、IP 质量和连接连续性对 AI 工具访问的影响。', url: '/blog/airport-use-cases/' },
      { title: 'AI 场景选择', description: '区分写作、搜索、研究、图像和自动化任务所需能力。', url: '/ai-tools/#directory' },
      { title: '隐私与账号安全', description: '避免提交敏感资料，检查数据保留、训练使用和团队权限设置。', url: '/about/' },
      { title: '费用比较方法', description: '比较免费额度、订阅费用、使用限制和团队协作成本。', url: '/compare/' },
      { title: '跨设备工作流', description: '规划桌面端、移动端和浏览器之间的资料同步与权限。', url: '/blog/airport-device-platform-guide/' },
      { title: '提交工具或勘误', description: '通过 Telegram 提交工具资料、更新信息或错误反馈。', url: '/contact/' },
    ],
    faqs: [
      { question: 'AI 工具推荐会只看热门程度吗？', answer: '不会。更重要的是任务匹配、结果质量、隐私设置、费用和持续可用性。' },
      { question: '为什么同一 AI 工具在不同地区体验不同？', answer: '服务地区政策、网络路由、账号状态和功能灰度可能不同，应以工具官方说明与实际账户状态为准。' },
      { question: '可以提交希望收录的工具吗？', answer: '可以，通过 Telegram @rumors6688 提交工具名称、官方地址、适用场景和希望补充的信息。' },
    ],
  },
  {
    slug: 'streaming', title: '流媒体工具推荐', eyebrow: 'Streaming Guide', icon: 'play',
    description: '整理平台地区、设备支持、画质需求、网络诊断与常见播放问题。',
    intro: '流媒体可用性受到账号地区、内容版权、设备认证、网络地址和平台政策影响。本站只提供信息整理与排查思路，不承诺任何第三方服务长期解锁特定平台。',
    highlights: ['区分账号与网络问题', '记录平台政策变化', '关注持续带宽与设备认证'],
    entries: [
      { title: '流媒体机场怎么选', description: '关注地区识别、持续带宽、节点更新和服务方说明。', url: '/blog/airport-use-cases/' },
      { title: '地区节点选择', description: '根据内容地区、物理距离与线路情况选择香港、日本、新加坡或美国节点。', url: '/blog/airport-regional-nodes/' },
      { title: '线路类型影响', description: '理解直连、中转与专线对高峰期播放稳定性的影响。', url: '/blog/airport-line-types/' },
      { title: '播放卡顿排查', description: '检查清晰度、持续带宽、DNS、节点负载和客户端代理模式。', url: '/blog/airport-troubleshooting/' },
      { title: '推荐与风险边界', description: '识别“永久解锁”等无法长期保证的宣传表述。', url: '/blog/airport-recommendations-2026/' },
      { title: '场景对比', description: '比较流媒体、游戏、AI 与办公对线路指标的不同要求。', url: '/compare/' },
    ],
    faqs: [
      { question: '能打开首页就代表完整解锁吗？', answer: '不代表。首页访问、搜索结果、具体片库和高清播放可能分别受到不同限制。' },
      { question: '播放卡顿一定是节点速度慢吗？', answer: '不一定，还可能与设备性能、应用缓存、Wi-Fi、账号地区、DNS 或平台服务器有关。' },
      { question: '为什么不承诺永久解锁？', answer: '平台识别规则和服务节点会变化，任何第三方都难以对长期状态作可靠保证。' },
    ],
  },
  {
    slug: 'apple-id', title: '苹果 ID 使用指南', eyebrow: 'Apple ID Resources', icon: 'globe',
    description: '提供地区账号、登录安全、双重认证、付款方式和常见错误的基础说明。',
    intro: '本站不公开共享他人的账号、密码或验证码。共享凭据存在隐私、设备锁定和资金风险。本栏目侧重介绍合规注册、自有账号管理、地区切换与安全注意事项。',
    highlights: ['不公开账号密码', '优先使用自有账号', '保护双重认证与设备安全'],
    entries: [
      { title: '使用前安全检查', description: '确认账号归属、双重认证、受信任设备与付款信息不会暴露。', url: '/apple-id/#directory' },
      { title: '地区与商店差异', description: '理解 Apple ID 地区、App Store 内容和付款方式之间的关系。', url: '/apple-id/#directory' },
      { title: '登录与退出注意事项', description: '不要在 iCloud 主账号中登录来历不明的共享凭据。', url: '/apple-id/#directory' },
      { title: '常见错误处理', description: '从网络、账号状态、地区设置和付款方式依次检查。', url: '/apple-id/#directory' },
      { title: '账号恢复', description: '优先使用 Apple 官方恢复流程，不向第三方提供验证码。', url: '/apple-id/#directory' },
      { title: '提交问题', description: '提供错误提示和系统版本，不要发送账号密码、验证码或付款信息。', url: '/contact/' },
    ],
    faqs: [
      { question: '本站会发布免费共享苹果 ID 和密码吗？', answer: '不会。公开共享凭据可能导致隐私泄露、设备锁定、账号争夺和资金风险。' },
      { question: '可以在 App Store 临时登录其他账号吗？', answer: '操作前应确认账号来源和用途，并避免在 iCloud 设置中登录不受信任账号；更稳妥的方式是使用自己的账号。' },
      { question: '遇到验证码问题怎么办？', answer: '只通过 Apple 官方流程处理，不向任何第三方发送验证码、恢复密钥或受信任设备信息。' },
    ],
  },
  {
    slug: 'free-nodes', title: '免费节点与公开资源', eyebrow: 'Public Resources', icon: 'layers',
    description: '解释公开节点的来源风险、使用限制、核验方法与更安全的替代选择。',
    intro: '本站不保证公开节点的隐私、速度和持续可用性，也不建议使用未知来源节点处理账号、支付、工作文件或其他敏感信息。使用任何公开资源前，都应了解运营主体、日志政策和潜在风险。',
    highlights: ['不处理敏感信息', '核验来源与更新时间', '默认视为不稳定资源'],
    entries: [
      { title: '公开资源风险说明', description: '了解流量可见性、日志、劫持、限速和随时失效等风险。', url: '/free-nodes/#directory' },
      { title: '订阅格式基础', description: '理解订阅地址、节点列表和客户端配置之间的关系。', url: '/blog/airport-subscription-guide/' },
      { title: '客户端安全检查', description: '只从可信来源获取客户端，并保留系统和浏览器安全设置。', url: '/blog/client-checklist/' },
      { title: '节点失效排查', description: '检查订阅更新时间、节点状态、客户端日志和本地网络。', url: '/blog/airport-troubleshooting/' },
      { title: '付费与免费方案比较', description: '从稳定性、支持、隐私和维护成本比较不同选择。', url: '/blog/airport-pricing-guide/' },
      { title: '报告失效或风险', description: '提交资源地址和发现时间，不要发送个人订阅或账号凭据。', url: '/contact/' },
    ],
    faqs: [
      { question: '免费节点适合长期使用吗？', answer: '通常不适合。公开资源容易拥堵、失效，运营和日志情况也可能不透明。' },
      { question: '可以用免费节点登录重要账号吗？', answer: '不建议。不要通过未知来源节点处理支付、邮箱、工作系统或包含个人信息的服务。' },
      { question: '为什么节点刚添加就失效？', answer: '公开节点使用人数多、维护不稳定，也可能因配置、网络或服务端限制迅速失效。' },
    ],
  },
  {
    slug: 'topics', title: '专题聚合', eyebrow: 'Topic Clusters', icon: 'grid',
    description: '把核心指南、细分问题、对比文章和 FAQ 组合成连续的学习路径。',
    intro: '专题页不是文章简单堆叠，而是按照“先理解概念、再做选择、随后配置、最后排错”的顺序组织内容。读者可以从一个核心问题出发，逐步补齐相关知识。',
    highlights: ['按学习顺序组织', '核心文章连接子问题', '避免重复与关键词堆砌'],
    entries: [
      { title: '新手机场入门', description: '选择方法、订阅导入、客户端安装和首次测试。', url: '/blog/airport-selection-guide/' },
      { title: '线路与协议', description: '直连、中转、IPLC、SS、V2Ray、Trojan 与客户端生态。', url: '/blog/airport-line-types/' },
      { title: '流媒体与 AI', description: '地区可用性、IP 质量、持续带宽和场景判断。', url: '/blog/airport-use-cases/' },
      { title: '价格与倍率', description: '付款周期、有效流量、倍率、流量包和设备限制。', url: '/blog/airport-pricing-guide/' },
      { title: '地区节点', description: '香港、日本、新加坡、美国和其他常见地区节点。', url: '/blog/airport-regional-nodes/' },
      { title: '故障排查', description: '订阅、节点、连接、网页、延迟和晚高峰问题。', url: '/blog/airport-troubleshooting/' },
    ],
    faqs: [
      { question: '专题和文章分类有什么区别？', answer: '分类按内容类型归档，专题则围绕一个问题将不同类型文章按阅读顺序连接。' },
      { question: '新手应该从哪个专题开始？', answer: '建议从“新手机场入门”开始，再根据自己的设备和场景进入线路、客户端或故障排查专题。' },
      { question: '专题内容会更新吗？', answer: '会。新增文章或重要规则变化后，会调整专题入口和阅读顺序。' },
    ],
  },
  {
    slug: 'brands', title: '品牌资料库', eyebrow: 'Brand Library', icon: 'tag',
    description: '集中整理服务和客户端的基本资料、入口、相关教程、风险提示与更新记录。',
    intro: '品牌资料页的目标不是只放一个注册按钮，而是回答“它是什么、适合谁、有哪些限制、从哪里进入、还需要阅读什么”。推广关系和外部跳转会明确标注。',
    highlights: ['推广关系明确', '资料与教程关联', '保留风险与更新说明'],
    entries: [
      { title: '光年梯资料入口', description: '查看服务入口及相关选择说明，具体套餐以服务方页面为准。', url: '/airport/#recommendations' },
      { title: '云图机场资料入口', description: '查看服务入口、推广标注和购买前核验事项。', url: '/airport/#recommendations' },
      { title: '鲲鹏加速资料入口', description: '查看服务入口、第三方跳转说明和相关教程。', url: '/airport/#recommendations' },
      { title: 'Clash 客户端资料', description: '了解客户端分支、配置格式、订阅导入和常见错误。', url: '/blog/airport-protocol-client-guide/' },
      { title: 'Shadowrocket 资料', description: '了解 iOS 使用场景、订阅导入与设备安全注意事项。', url: '/blog/airport-device-platform-guide/' },
      { title: 'sing-box 资料', description: '了解协议支持、客户端生态和与订阅格式的关系。', url: '/blog/airport-protocol-client-guide/' },
    ],
    faqs: [
      { question: '品牌资料页是否等于推荐？', answer: '不等于。资料收录用于集中整理信息，是否包含推广关系会单独标注。' },
      { question: '为什么不直接复制服务方宣传？', answer: '宣传信息需要核验，并与实际测试、限制条件和风险提示分开呈现。' },
      { question: '如何提交品牌资料更新？', answer: '通过 Telegram @rumors6688 提交页面地址、需要修改的位置和可核验来源。' },
    ],
  },
  {
    slug: 'compare', title: '产品与服务对比', eyebrow: 'Comparisons', icon: 'compare',
    description: '使用一致的维度比较线路、价格、客户端、设备限制和适用场景。',
    intro: '对比表负责快速扫描差异，正文负责解释条件与边界。对于无法稳定量化的体验，不使用单一分数替代真实说明，也不会把不同测试环境的数据直接混在一起。',
    highlights: ['统一比较口径', '说明测试条件', '结论对应具体人群'],
    entries: [
      { title: '机场与 VPN 区别', description: '从使用方式、控制程度、配置成本和适用人群理解两者差异。', url: '/blog/airport-vpn-vps-comparison/' },
      { title: '机场与自建 VPS', description: '比较维护成本、IP 资源、线路选择和故障处理责任。', url: '/blog/airport-vpn-vps-comparison/' },
      { title: 'IPLC 与中转', description: '理解线路结构、稳定性、价格和真实性核验方法。', url: '/blog/airport-line-types/' },
      { title: '不同客户端比较', description: '按平台、协议、维护状态和配置复杂度选择客户端。', url: '/blog/airport-protocol-client-guide/' },
      { title: '月付与年付', description: '比较折扣、资金风险、服务变化和实际使用周期。', url: '/blog/airport-pricing-guide/' },
      { title: '对比维度清单', description: '使用统一表格记录信息来源、测试日期和选择结论。', url: '/blog/comparison-dimensions/' },
    ],
    faqs: [
      { question: '对比表里的项目越多越好吗？', answer: '不是。应优先保留会影响选择的维度，并说明数据时间和来源。' },
      { question: '可以直接根据总分购买吗？', answer: '不建议。总分会掩盖不同需求，应该先确定自己的关键指标和不能接受的限制。' },
      { question: '如何比较不同时间的测速结果？', answer: '必须尽量保持地区、运营商、设备、客户端、时段和测试方法一致。' },
    ],
  },
  {
    slug: 'about', title: '关于我们', eyebrow: 'About Jichangtu', icon: 'sparkles',
    description: '了解机场图的内容原则、更新机制、推广标注、隐私边界与联系渠道。',
    intro: '机场图是面向中文用户的网络工具与数字生活内容站。我们希望用温和、清晰、可持续维护的方式整理复杂信息，让读者在看到推荐之前先理解选择条件、风险与限制。',
    highlights: ['读者问题优先', '推广关系透明', '错误可反馈、内容可修订'],
    entries: [
      { title: '内容原则', description: '先回答问题，再提供延伸阅读；不使用无法核验的绝对化承诺。', url: '/about/#directory' },
      { title: '编辑流程', description: '整理搜索意图、核对资料、建立结构、加入内链并进行构建检查。', url: '/about/#directory' },
      { title: '更新机制', description: '对价格、入口、软件版本和平台规则等易变信息标记更新时间。', url: '/about/#directory' },
      { title: '推广说明', description: '带推广参数的外部链接会明确标注，读者不因此支付额外费用。', url: '/about/#directory' },
      { title: '勘误与合作', description: '提交页面地址、问题位置和可核验资料，便于快速处理。', url: '/contact/' },
      { title: '免责声明', description: '本站内容用于信息整理，不构成对第三方服务的持续可用性承诺。', url: '/about/#directory' },
    ],
    faqs: [
      { question: '机场图是什么类型的网站？', answer: '这是一个中文内容站，主要整理机场选择、客户端教程、故障排查、数字工具和相关基础知识。' },
      { question: '推广链接会影响内容结论吗？', answer: '推广关系会明确标注，内容仍应保留选择条件、限制、风险提示和可核验信息。' },
      { question: '如何联系机场图？', answer: '通过 Telegram @rumors6688 联系，可用于勘误、资料更新、收录建议和合作沟通。' },
    ],
  },
];
