export default {
  name: '机场图',
  shortName: '机场图',
  tagline: '可靠、克制的中文网络工具指南',
  description: '机场图为中文用户整理机场推荐、线路与协议知识、客户端教程、故障排查和数字工具指南，强调清晰来源、风险提示与持续更新。',
  url: 'https://jichangtu.com',
  language: 'zh-CN',
  locale: 'zh_CN',
  author: '机场图编辑部',
  telegram: '@rumors6688',
  telegramUrl: 'https://t.me/rumors6688',
  currentYear: new Date().getFullYear(),
  defaultSchemaJson: JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: '机场图',
    url: 'https://jichangtu.com',
    description: '机场图为中文用户整理机场推荐、线路与协议知识、客户端教程、故障排查和数字工具指南。',
    inLanguage: 'zh-CN',
  }),
};
